stages:
 - deb
 - deploy

deb:
  image: debian:stretch
  stage: deb
  tags:
    - docker
  script:
   - apt-get update
   - apt-get install -y git git-core bundler rake libxml2-dev autoconf bison build-essential libssl-dev libmysqlclient-dev libxslt-dev nodejs libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev curl pkg-config debhelper gem2deb
   - bundle install --path vendor/bundle
   - rake package:build:debian
  artifacts:
    paths:
    - pkg/g5k-checks*.deb
    expire_in: '1 day'

push-package:
  stage: deploy
  # tags must be 'packages' so that we use the runner on packages.grid5000.fr
  tags:
    - packages
  only: # we only execute this job for tagged commits
    - tags
  script:
    - g5k-deploy-files --files 'pkg/g5k-checks_*.deb' --directory deb/g5k-checks
