#!/usr/bin/ruby

# This is a script to test g5k-checks on a node, executed from a gitlab-ci runner

# You can alter the ruby-cute query parameters using env variables TARGET_<pararmeter>

gem 'ruby-cute', ">=0.11"
require 'cute'
require 'net/scp'
require 'pp'
require 'logger'

if ARGV.length < 1
  puts "Too few arguments (please provide which distro you want to test)"
  exit false
end

g5k = Cute::G5K::API.new
logger = Logger.new(STDOUT)
STDERR.reopen(STDOUT)
STDOUT.sync = true

logger.info("Dumping CI_* ENV variables:")
puts ENV.to_a.select { |e| e[0] =~ /^CI_/ }.map { |e| e.join(' ') }.join("\n")
logger.info("Dumping TARGET_* ENV variables:")
puts ENV.to_a.select { |e| e[0] =~ /^TARGET_/ }.map { |e| e.join(' ') }.join("\n")
logger.info("Reserving node...")
job_attr = {
  :site => 'nancy',
  :queue => 'production',
  :nodes => 1,
  :walltime => '0:15',
  :type => :allow_classic_ssh,
  :wait => true,
  :name => 'gitlab g5k-checks'
}
# Pull modified parameters from environment variables
ENV.select {|k,_| k.start_with?('TARGET_')}.each do |k,v|
  sym = k.split('_').last.downcase.to_sym
  job_attr[sym] = v
  logger.debug("Updating parameter #{sym} with: #{k}=#{v}")
end
logger.info("Job args: #{job_attr}")
job = g5k.reserve(**job_attr)
logger.info("Job #{job['uid']} created.")
node = job['assigned_nodes'].first
logger.info("Running on: #{node}")
logger.info("Running sudo-g5k")
ssh = Net::SSH::start(node, g5k.g5k_user, {:keys => ['/home/gitlab-runner/.ssh/id_rsa']})
ssh.exec3!("sudo-g5k")
scp = Net::SCP.start(node, g5k.g5k_user)
gl = Dir::glob("#{ARGV[0]}/g5k-checks_*_amd64.deb")
if gl.length != 1
  raise "no file to upload"
end
logger.info("Copying and installing artifact")
scp.upload!(gl.first, "/tmp/g5k-checks.deb")
ssh.exec3!('sudo apt install -y -o Dpkg::Options::="--force-confnew" --allow-downgrades /tmp/g5k-checks.deb')
logger.info("Running g5k-checks")
ssh.exec3!('sudo g5k-checks --remove-tests="User used sudo-g5k" -v')
ssh.close
g5k.release(job)
