#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
g5k-checks -o `dirname $CHECKLOGFILE`
ret=$?
if [ $ret -ne 0 ]; then
  echo "g5k-checks exited with code $ret, != 0" > $CHECKLOGFILE
fi
